name: learn-github-actions

on: 
  #æ‰‹åŠ¨è§¦å‘
  workflow_dispatch:

jobs:
  first-run-test:
    #æŒ‡å®šè¿ç®—ç¯å¢ƒï¼Œæœ€æ–°çš„Ubuntuä¸‹
    runs-on: ubuntu-latest
    steps:
      #æ‰§è¡Œ bash å‘½ä»¤
      - run: echo "ğŸ§ hello,this is my first step!"
